### ISSUE TITLE
klikken op user website gaat naar verkeerde url

### ISSUE THREAD

**Issue by iamgoodbytes** [thomasmore-imd/one.weareimd.be#13]
http://one.weareimd.be/profile/75

klik op erhanlammar.be -> je komt uit op one.weareimd.be, wellicht om dat http:// mankeert op de link

**Comment by hansvn** [comment]
verander
```
<a href="{{ $user->website }}" target="_blank">{{ $user->website }}</a>
```
in
```
<a href="{{ URL::to($user->website) }}" target="_blank">{{ $user->website }}</a>
```
en dit zal je problemen oplossen ;)

**Comment by thomasdbock** [comment]
Elke IMDer zou moeten weten dat URL's met 'http://' beginnen zoals gezegd in de placeholder.
Voor diegene die het toch negeren, fixed controle op http voor het printen van de url.
