### ISSUE TITLE
Project blocks need fixed height to prevent disrupted floating

### ISSUE THREAD

**Issue by axelvnk** [thomasmore-imd/one.weareimd.be#2]
On the project overview page : 

When the project info has more characters, the block becomes longer causing the blocks to float badly. This results in an empty row with only one block floated to the right. 

The blocks need a fixed height, maybe limited characters on owner name.

**Comment by iamgoodbytes** [comment]
Hi @axelvnk, can you submit a pull request so that we can deploy this?

**Comment by axelvnk** [comment]
I will try and make time this evening. Maybe there should be some guidelines added to this project about contributing. Something like this : http://docs.sylius.org/en/latest/contributing/code/patches.html

Commit message structure like so : [ISSUE###] Component : Performed action
Maybe provide some component names that people can pick from so we have more uniformity in the commits.
